version: '3.8'

services:
  kanban_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - kanban_db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=kanban_db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  kanban_db:
    image: mysql:5.7
    container_name: kanban_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: projects
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root